_veh = _this select 0;

_veh addItemcargoglobal ["rhs_30Rnd_545x39_7N22_AK", 15]; 
_veh addItemcargoglobal ["rhs_30Rnd_545x39_AK_green", 10]; 
_veh addMagazinecargoglobal ["rhs_mag_rgd5", 14];  
_veh addMagazinecargoglobal ["rhs_mag_rdg2_white", 21];
_veh addItemcargoglobal ["rhs_VOG25", 24];  
_veh addItemcargoglobal ["rhs_GRD40_White", 16];  
_veh addItemcargoglobal ["rhs_10Rnd_762x54mmR_7N14", 10]; 
_veh addItemcargoglobal ["rhs_100Rnd_762x54mmR", 5];
_veh addWeaponCargoGlobal ["rhs_weap_rsp30_white", 7];
_veh addWeaponCargoGlobal ["rhs_weap_rsp30_red", 5];
_veh addWeaponCargoGlobal ["rhs_weap_rsp30_green", 5];
_veh addWeaponcargoGlobal ["rhs_weap_rshg2", 1];
_veh addItemCargoGlobal ["ACE_elasticBandage",24];
_veh addItemCargoGlobal ["ACE_packingBandage",24];
_veh addItemCargoGlobal ["ACE_quikclot",24];
_veh addItemCargoGlobal ["ACE_epinephrine",12]; 
_veh addItemCargoGlobal ["ACE_fieldDressing",24];
_veh addItemCargoGlobal ["ACE_morphine",12];